### ISSUE TITLE
[CSS] Portfolio Website Help - Box Items do not respond to Resizing well

### ISSUE THREAD

**Issue by JasonHannanto** [JasonHannanto/JasonHannanto.github.io#1]
## Hacktoberfest Contributions 
So it's Hacktoberfest, and you get a free t-shirt for making 4 pull requests! If anyone would love to help me out with an issue on my website I'd gladly appreciate the generosity. Your help will definitely be credited and the issues I have shouldn't be too difficult to solve.

## Issue
Upon resize, items inside skill cards will not respond well. 

## Steps to recreate Issue
1. Open up website. (https://jasonhannanto.github.io/)
2. Go to "Skills" section
3. Resize your window horizontally

## Contributing
Feel free to change the CSS/HTML for the skill cards as much as you want as long as it's within a reasonable scope. Creative inputs are always open.

**Comment by Adroit11** [comment]
Did like to help on this

**Comment by RitikPatni** [comment]
How do you want them to look like??

**Comment by JasonHannanto** [comment]
![screenshot 20](https://user-images.githubusercontent.com/28082594/31064533-0563725c-a6f2-11e7-8f9f-ff0705955445.png)

Items should remain in their place when resizing (Possibly by not reducing the width of the cards when resizing) however maintaining bootstrap's column resizing function

Tip: Right now I have the items on Float:Left, and I believe I have a Width:100% on one of the divs...

**Comment by RakshithNM** [comment]
Is anybody working on this yet?

**Comment by JasonHannanto** [comment]
@RakshithNM If you would like to work on it or have ideas, please feel free to give it a try. One other person is also working on it still I believe.

**Comment by RakshithNM** [comment]
Ok, so you want the items to be of the same size in all viewport sizes?

**Comment by JasonHannanto** [comment]
@RakshithNM I'm thinking of the best way to design it.. and I guess I would be okay if the cards do stay the same size, however maintain bootstrap's column resizing function. I'm sure there's a better design option here.. but atleast for the scope of this project that would be good enough.

Reason why I dont want the cards width to resize is that it pushes the element items inside it around (Because it's messy). So not changing the width would be the easiest way here I guess.

**Comment by RakshithNM** [comment]
Ok, what you want here is that the inner items should stay the same and also the page should be responsive!

**Comment by Athyk** [comment]
Is the problem already solved or can I help you with anything? @JasonHannanto
