### ISSUE TITLE
[Feat][Beginner-Friendly] Make button glow when hovered over

### ISSUE THREAD

**Issue by JasonHannanto** [JasonHannanto/JasonHannanto.github.io#11]
## Hacktoberfest Contributions 
So it's Hacktoberfest, and you get a free t-shirt for making 4 pull requests! If anyone would love to help me out with an issue on my website I'd gladly appreciate the generosity. Your help will definitely be credited and the issues I have shouldn't be too difficult to solve.

## Feature
1. Upon Hovering over the "Blog" button -> it should glow/pulse a different color. 
2. Transition time should be smooth [not too fast & not too slow]
3. **BONUS**: If you are creative and know how to make it "pulse" so that it looks animated when hovering over, it would be AWESOME!
4. Color: I'm thinking it would look nice if you change the color to a nice warm/light shade of orange. But if you see a better color please give the idea.

![screenshot 26](https://user-images.githubusercontent.com/28082594/31088480-a768ea42-a755-11e7-9116-57294499bbce.png)

## Contributing
You can make changes to the HTML/CSS/JS files as long as it is within the scope of this change. You can also create an ID tag.

**Comment by okatticus** [comment]
I'd like to work on this.

**Comment by JasonHannanto** [comment]
@okatticus Feel free to start working on it.

**Comment by rowhitswami** [comment]
Can I show my creativity on your website? :blush:

**Comment by JasonHannanto** [comment]
@rowhitswami Would you mean giving me an idea of what you have in mind?

**Comment by okatticus** [comment]
#12 I have made the button color change on hovering. Let me know what you think of the color.

**Comment by JasonHannanto** [comment]
@okatticus Hi thanks, but can you make the style changes in the css file thanks

**Comment by rowhitswami** [comment]
@JasonHannanto  I mean layout design, some hovering and shadow effect, and icons.

**Comment by okatticus** [comment]
@JasonHannanto  Could you please elaborate what kind of style changes are to be made?

**Comment by JasonHannanto** [comment]
@okatticus Sorry I was looking at the wrong pull request, I'll merge your commit thanks

**Comment by okatticus** [comment]
@JasonHannanto Thanks a lot, Jason. :)

**Comment by rowhitswami** [comment]
please merge so that I can start working on new things.

**Comment by francistaberdo** [comment]
i'd like to help you out with this. maybe improve the overall look of the site as well because it feels too inconsistent. just give me a go signal and i'll start 👍

**Comment by JasonHannanto** [comment]
This issue has been solved, thanks everyone who helped as for further changes I may post more issues!
